### PR TITLE
Improvements and Support for [XFA] RM Marketplace

### PR DESCRIPTION
**Pull request by apkreader**
This has various improvements, also adds explanations to the inputFields so people can understand it easier.
This mainly also adds support for customer payment profiles using the RM Marketplace addon.

Without the template modification it wont be possible for third party sellers to add their BTCPay details here:
image

Below how it looks with the required template modification:
image

It would result in the following error:
image

My commits fix these and also properly implement the templates and phrases.
If you need any more informations or want to see it live working, please let me know.

Thanks, sincerly brownie

### CODE REVIEW

**Comment by xBrownieCodezV2** [comment]
merge?

**Comment by 021-projects** [comment]
Hello, my friend!

Thank you very much for waiting, I now have some difficulties in my life that do not allow me to do anything other than solve them 😬 

https://github.com/btcpayserver/xenforo/pull/6/commits/5b735aa20acfb67e96f5c8fd7edb1ab67bce2552 – Why do we need this? The add-on has been tested with version 2.3 and does not seem to need a package update. Unnecessary updates can lead to new bugs and conflicts, which is what we don’t want) Also `composer.lock` reduces the "it works on my machine" problem, where code works on one developer’s setup but fails on another’s due to different dependency versions.

https://github.com/btcpayserver/xenforo/pull/6/commits/926136eef3134b462b1091184fbd8cbc0084434c – XenForo exports data to XML when building the add-on; it is not generated at the time of development – this means that these are actually files for production. That is, it’s like the `dist` directory in JS projects, if you know what I mean. To avoid desync between the actual add-on data and the XML data, I decided to simply not include the `_data` folder in the project, otherwise the developers would have to manually export changes to templates and phrases on every commit. 

https://github.com/btcpayserver/xenforo/pull/6/commits/b074923d869a0948cdc5b9f675eed767415033d1 – Apparently, [XFA] RM Marketplace already supports BTCPay, and for some reason your modification simply replaces the names of the input fields - I’m not entirely clear how this should work. Anyway, the goal of this project is to integrate BTCPay with XenForo, and [XFA] RM Marketplace is produced by a third party developer. If we add support for this add-on, this means that we need to purchase a license for it and constantly monitor compatibility. Therefore, I would prefer to make your solution in a separate add-on. 
P.S. You mentioned in the comment:
> i hate the xenforo template system so much, i hope oneday someone fixes it, this actually so bad, one fucking additional space breaks everything
The problem is probably that you are working with XML files directly (judging by the fact that you left a comment in the file that is automatically generated). XenForo assumes that you will do all work with templates and modifications through the control panel.

But! 
https://github.com/btcpayserver/xenforo/pull/6/commits/a837b047c70fdaae12b712cbfc6eb4bddd2c400f – I found this commit very usefull. I'll probably add your explanations when I have some free time to make sure I don't break anything during the update :) At this time I will leave this request open so as not to forget.

Thank you for your participation in the project!

**Comment by xBrownieCodezV2** [comment]
Hi, and thanks for reply.
Please check again for XFA RM Marketplace compatibility, i created a new templarte to make it work.
Ive attached a screenshot of the issue above.

Thanks, sincerly
Brownie

**Review by 021-projects — COMMENTED** [review]
Hello, my friend!

Thank you very much for waiting, I now have some difficulties in my life that do not allow me to do anything other than solve them 😬 

https://github.com/btcpayserver/xenforo/pull/6/commits/5b735aa20acfb67e96f5c8fd7edb1ab67bce2552 – Why do we need this? The add-on has been tested with version 2.3 and does not seem to need a package update. Unnecessary updates can lead to new bugs and conflicts, which is what we don’t want) Also `composer.lock` reduces the "it works on my machine" problem, where code works on one developer’s setup but fails on another’s due to different dependency versions.

https://github.com/btcpayserver/xenforo/pull/6/commits/926136eef3134b462b1091184fbd8cbc0084434c – XenForo exports data to XML when building the add-on; it is not generated at the time of development – this means that these are actually files for production. That is, it’s like the `dist` directory in JS projects, if you know what I mean. To avoid desync between the actual add-on data and the XML data, I decided to simply not include the `_data` folder in the project, otherwise the developers would have to manually export changes to templates and phrases on every commit. 

https://github.com/btcpayserver/xenforo/pull/6/commits/b074923d869a0948cdc5b9f675eed767415033d1 – Apparently, [XFA] RM Marketplace already supports BTCPay, and for some reason your modification simply replaces the names of the input fields - I’m not entirely clear how this should work. Anyway, the goal of this project is to integrate BTCPay with XenForo, and [XFA] RM Marketplace is produced by a third party developer. If we add support for this add-on, this means that we need to purchase a license for it and constantly monitor compatibility. Therefore, I would prefer to make your solution in a separate add-on. 
P.S. You mentioned in the comment:
> i hate the xenforo template system so much, i hope oneday someone fixes it, this actually so bad, one fucking additional space breaks everything

The problem is probably that you are working with XML files directly (judging by the fact that you left a comment in the file that is automatically generated). XenForo assumes that you will do all work with templates and modifications through the control panel.

But! 
https://github.com/btcpayserver/xenforo/pull/6/commits/a837b047c70fdaae12b712cbfc6eb4bddd2c400f – I found this commit very usefull. I'll probably add your explanations when I have some free time to make sure I don't break anything during the update :) At this time I will leave this request open so as not to forget.

Thank you for your participation in the project!

**Comment by 021-projects** [comment]
> Hi, and thanks for reply. Please check again for XFA RM Marketplace compatibility, i created a new templarte to make it work. Ive attached a screenshot of the issue above.
> 
> Thanks, sincerly Brownie

Judging by the screenshots, the error is not related to this project. This is a bug in [XFA] RM Marketplace. But I already commented on this point:
> Anyway, the goal of this project is to integrate BTCPay with XenForo, and [XFA] RM Marketplace is produced by a third party developer. If we add support for this add-on, this means that we need to purchase a license for it and constantly monitor compatibility. Therefore, I would prefer to make your solution in a separate add-on.

**Comment by xBrownieCodezV2** [comment]
Hi, thanks for your time,, il just keep my fork then
Sincerly brownie

**Pull request closed without merging**
